version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/joway/kuafu
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-golang-deps-{{ checksum "go.sum" }}
      - run: sudo apt update && sudo apt install -y gcc
      - run: ./bin/dep.sh
      - run: env GO111MODULE=on go build
      - run: env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: v1-golang-deps-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"
            - "vendor"
workflows:
  version: 2
  pipeline:
    jobs:
      - build
